const combatants = [
        {
            "id":"dog",
            "name":"Dog",
            "icon":"🐶",
            "maxHealth":16,
            "damageMultiplier":0.9,
            "defenseMultiplier":0.8,
            "resistanceMultiplier":1.5,
            "magDefenseMultiplier":1.0,
            "magicMultiplier":0.4,
            "baseMovepool":[
                "fierce_bark",
                "bite",
                "grip_jaw",
                "scratch",
                "escape"
            ]
        },
        {
            "id":"cat",
            "name":"Cat",
            "icon":"😺",
            "maxHealth":8,
            "damageMultiplier":1.2,
            "defenseMultiplier":1.5,
            "resistanceMultiplier":0.8,
            "magDefenseMultiplier":0.5,
            "magicMultiplier":0.9,
            "baseMovepool":[
                "bite",
                "scratch",
                "escape"
            ]
        },
        {
            "id":"alien",
            "name":"Alien Friend",
            "icon":"👾",
            "maxHealth":2,
            "damageMultiplier":1.5,
            "defenseMultiplier":1.5,
            "resistanceMultiplier":0.8,
            "magDefenseMultiplier":0.5,
            "magicMultiplier":2,
            "baseMovepool":[
                "alien_blast",
                "",
                "",
            ]
        }
    ];